from admin.questions_settings.q_settings import q_settings_handler
from admin.questions_settings.add_q import add_q_handler
from admin.questions_settings.add_category import add_cat_handler
from admin.questions_settings.add_choice import add_choice_handler
from admin.questions_settings.remove_category import remove_cat_handler
from admin.questions_settings.remove_choice import remove_choice_handler
from admin.questions_settings.remove_q import remove_q_handler
from admin.questions_settings.update_q import update_q_handler
