from models.DB import create_tables
from models.Admin import Admin
from models.BaseUser import BaseUser
from models.User import User
from models.Question import Question
from models.Choice import Choice
from models.Category import Category
from models.TestResult import TestResult
from models.TestQuestion import TestQuestion